POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "admin",
    "name": "test",
    "password": "root"
}
###
GET http://localhost:3001/api/users/63c17f15025f8c172f2dd94c